# Dependencies
gems: [jekyll-paginate, jekyll-gist]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Khizer Naeem
tagline:          'Linux, Windows, Cloud and Devops'
description:      'Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.'
url:              http://kxr.me
baseurl:          /

author:
  name:           'Khizer Naeem'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kxr
