plugins:
        - jekyll-paginate
        - jekyll-gist

markdown: kramdown
highlighter: rouge
kramdown:
        input: GFM
        hard_wrap: false
        syntax_highlighter: rouge
        coderay_wrap: nil

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Khizer Naeem
tagline:          'Linux, Windows, Cloud and Devops'
description:      'A Linux Systems Engineer, Cloud Architect, and DevOps enthusiast who loves automation, monitoring and stress testing perferably in the realms of Open Source.'
url:              http://kxr.me
baseurl:          /

author:
  name:           'Khizer Naeem'

paginate:         7

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kxr
