# Dependencies
gems: [jekyll-paginate, jekyll-gist]
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Khizer Naeem
tagline:          'Linux, Windows, Cloud and Devops'
description:      'A Linux Systems Engineer, Cloud Architect, and DevOps enthusiast who loves automation, monitoring and stress testing perferably in the realms of Open Source.'
url:              http://kxr.me
baseurl:          /

author:
  name:           'Khizer Naeem'
  url:            https://twitter.com/mdo

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kxr
