plugins:
    - jekyll-paginate
    - jekyll-gist

highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge

permalink: pretty

title: Khizer Naeem
tagline: Linux Cloud and Devops
description: >
    A Linux Systems Engineer, Cloud Architect, and DevOps enthusiast who loves automation,
    monitoring and stress testing perferably in the realms of Open Source. <br/>
    Currently working as Technical Account Manager (TAM) @ Red Hat.

url:              http://kxr.me
baseurl:          /

author:
  name:           'Khizer Naeem'

paginate:         7

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kxr
